Repository ladybug-tools/ladybug-rhino, pull requests merged in 2020-10, with the labels that each got.

#101 feat(export): add exporting component icons
  ladybug_rhino/versioning/export.py
Labels: enhancement

#103 feat(grasshopper): Add function for a document counter
  ladybug_rhino/grasshopper.py
  ladybug_rhino/viewport.py
Labels: enhancement

#104 feat(versioning): Have sync component update inputs + outputs
  ladybug_rhino/versioning/diff.py
Labels: enhancement

#106 feat(intersect): Add option for max_dist to line intersection function
  ladybug_rhino/intersect.py
Labels: enhancement

#108 feat(viewport): Add methods to capture view to file
  ladybug_rhino/grasshopper.py
  ladybug_rhino/viewport.py
Labels: enhancement, new development

#109 fix(geometry): Add extra check for duplicate vertices
  ladybug_rhino/fromgeometry.py
  ladybug_rhino/planarize.py
  ladybug_rhino/togeometry.py
Labels: bug, documentation, enhancement

#110 fix(pythonpath): Search for all settings-Scheme files
  ladybug_rhino/pythonpath.py
Labels: enhancement

#112 fix(fromobjects): Rotate compass text with the North
  ladybug_rhino/fromgeometry.py
  ladybug_rhino/fromobjects.py
  ladybug_rhino/togeometry.py
Labels: enhancement
