Repository ladybug-tools/ladybug-rhino, pull requests merged in 2020-11, with the labels that each got.

#114 chore(dev-deps): Include importlib-metadata in dev-requirements
  README.md
  dev-requirements.txt
Labels: dependencies

#115 fix(fromgeometry) : Add hole curves along with boundary curve
  ladybug_rhino/fromgeometry.py
Labels: bug

#118 fix(fromgeometry): Fix bug introduced by previous PRs
  ladybug_rhino/fromgeometry.py
Labels: bug

#119 fix(togeometry): Bug fix to previous commit
  ladybug_rhino/fromgeometry.py
Labels: bug

#124 feat(togeometry): Add methods for joined polylines
  ladybug_rhino/fromgeometry.py
Labels: new development
